/* Definition von Codierungen von Zeichen als Konstanten
und von zu akzeptierenden Mengen von Zeichen.*/

/*Buchstaben*/
#define CODE_A ".-"
#define CODE_B "-..."
#define CODE_C "-.-."
#define CODE_D "-.."
#define CODE_E "."
#define CODE_F "..-."
#define CODE_G "--."
#define CODE_H "...."
#define CODE_I ".."
#define CODE_J ".---"
#define CODE_K "-.-"
#define CODE_L ".-.."
#define CODE_M "--"
#define CODE_N "-."
#define CODE_O "---"
#define CODE_P ".--."
#define CODE_Q "--.-"
#define CODE_R ".-."
#define CODE_S "..."
#define CODE_T "-"
#define CODE_U "..-"
#define CODE_V "...-"
#define CODE_W ".--"
#define CODE_X "-..-"
#define CODE_Y "-.--"
#define CODE_Z "--.."

/*Sonderbuchstaben*/
/*Sind NICHT durch char darstellbar*/
#define CODE_A_GRAV ".--.-"
#define CODE_A_RING ".--.-"
#define CODE_A_UMLT ".-.-"
#define CODE_E_GRAV ".-..-"
#define CODE_E_ACUT "..-.."
#define CODE_O_UMLT "---."
#define CODE_U_UMLT "..--"
#define CODE_S_ZED "...--.."
#define CODE_CH "----"
#define CODE_N_TILD "--.--"

/*Zahlen*/
#define CODE_1 ".----"
#define CODE_2 "..---"
#define CODE_3 "...--"
#define CODE_4 "....-"
#define CODE_5 "....."
#define CODE_6 "-...."
#define CODE_7 "--..."
#define CODE_8 "---.."
#define CODE_9 "----."
#define CODE_0 "-----"

/*Satzzeichen*/
#define CODE_PUNKT ".-.-.-"
#define CODE_KOMMA "--..--"
#define CODE_COLON "---..."
#define CODE_SEMIC "-.-.-."
#define CODE_QMARK "..--.."
#define CODE_EMARK "-.-.--"
#define CODE_MINUS "-....-"
#define CODE_UNDSC "..--.-"
#define CODE_PAROP "-.--."
#define CODE_PARCL "-.--.-"
#define CODE_SQUOT ".----."
#define CODE_DQUOT ".-..-."
#define CODE_EQUAL "-...-"
#define CODE_PLUSZ ".-.-."
#define CODE_SLASH "-..-."
#define CODE_ATSYM ".--.-."

#define ZEICH_TREN " "
#define WORT_TREN "/"

/*Akzeptabelen Zeichen*/
#define ENCODABLE "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,:;?!-_()'\"=+/@ "
#define DECODABLE ".-/ "
